module.exports = {
  quotesLow: ['It appears not much phases you.',
              'You watch too many movies.',
              'You are a heartless just like the Kanye West song.'],
  quotesMed: ['Seems like you have a good head on your shoulders.',
              'You need to have a shot of whiskey.',
              'It sounds about right.'],
  quotesHigh: ['You must have had a sheltered childhood.',
               'You should consider a career in politics.',
               'You are a raging sociopath.'],
  quotesOmg: ['ARE YOU MAD?!',
              'Put down the alcohol please.',
              '...I have no words.'],
  ratedGlow: ['This sounds about right.',
              'You rated it just like the MPAA. Boring.',
              'You probably watch a lot of Disney movies.'],
  ratedGmed: ['You probably think it deserved a PG rating.',
              'You likely felt the content is a bit strong for kids',
              'You might be a little sensitive there.'],
  ratedGhigh: ['Wow, was it really that bad?',
              ''],
  ratedPGlow: ['You might be a little desensitized',
               '']
}
