module.exports = {
    "G": {
        1: ['This sounds about right.',
            'You rated it just like the MPAA. Boring.',
            'You probably watch a lot of Disney movies.'],
        2: ['You probably think it deserved a PG rating.',
            'You likely felt the content is a bit strong for kids',
            'You might be a little sensitive there.'],
        3: ['Wow, was it really that bad?',
            'You should consider a career in politics.'],
        4: ['ARE YOU MAD?!',
            'Put down the alcohol please.',
            '...I have no words.']
    },
    "PG": {
        1: ['You might be a little desensitized.',
            'You probably watch a lot of Disney movies.'],
        2: ['You are right on the money.',
            'This sounds about right.'],
        3: ['You probably think it deserved a PG-13 rating.',
            'You likely felt the content is a bit strong for kids',
            'You might be a little sensitive there.'],
        4: ['ARE YOU MAD?!',
            'Put down the alcohol please.',
            '...I have no words.']
    },
    "PG-13": {
        1: ['This sounds about right.',
            'You rated it just like the MPAA. Boring.',
            'You probably watch a lot of Disney movies.'],
        2: ['You probably think it deserved a PG rating.',
            'You likely felt the content is a bit strong for kids'],
        3: ['Sounds about right.',
            'You are right on the mark.',
            'Good job. This is about what a PG-13 movie should be.'],
        4: ['You probably think it deserved a R rating.',
            '...I have no words.',
            'Wow, was it really that bad?']
    },
    "R": {
        1: ['You are pretty desensitized.',
            'Are you dead to the world?',
            'Wow...',
            'You kick puppies.'],
        2: ['You must have played Duke Nukem a lot.',
            'You might need a little talking to.'],
        3: ['You go hardcore.',
            'You see this all the time.',
            'Tough guy, huh?'],
        4: ['Sounds about right.',
            'You are right on the mark.',
            'Good job. This is about what a R rated movie should be.']
    },
  quotesLow: ['It appears not much phases you.',
              'You watch too many movies.',
              'You are a heartless just like the Kanye West song.'],
  quotesMed: ['Seems like you have a good head on your shoulders.',
              'You need to have a shot of whiskey.',
              'It sounds about right.'],
  quotesHigh: ['You must have had a sheltered childhood.',
               'You should consider a career in politics.',
               'You are a raging sociopath.'],
  quotesOmg: ['ARE YOU MAD?!',
              'Put down the alcohol please.',
              '...I have no words.'],
  ratedGlow: ['This sounds about right.',
              'You rated it just like the MPAA. Boring.',
              'You probably watch a lot of Disney movies.'],
  ratedGmed: ['You probably think it deserved a PG rating.',
              'You likely felt the content is a bit strong for kids',
              'You might be a little sensitive there.'],
  ratedGhigh: ['Wow, was it really that bad?',
              ''],
  ratedPGlow: ['You might be a little desensitized',
               '']
}
